[build]
  publish = "."

[[redirects]]
  from = "/aviso-legal"
  to = "/aviso-legal.html"
  status = 200

[[redirects]]
  from = "/privacidad"
  to = "/privacidad.html"
  status = 200

[[redirects]]
  from = "/cookies"
  to = "/cookies.html"
  status = 200

[[redirects]]
  from = "/gracias"
  to = "/gracias.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
